[workspace]
authors = ["Raheem Hashmani <hashmani@wisc.edu>"]
channels = ["conda-forge"]
name = "example"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"


[tasks.lab]
description = "Launch JupyterLab"
cmd = "jupyter lab"

[tasks.start]
description = "Start exploring the Pixi project"
depends-on = ["lab"]

[dependencies]
python = ">=3.13.5,<3.14"
numpy = ">=2.3.0,<3"
notebook = ">=7.4.3,<8"
jupyterlab = ">=4.4.3,<5"

[feature.dev.dependencies]
pre-commit = ">=4.2.0,<5"

[environments]
dev = ["dev"]
